name: bellfinder
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+23

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.22.1
  drift_flutter: ^0.2.3
  path: ^1.9.0
  provider: ^6.1.2
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  package_info_plus: ^8.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.16
  flutter_map_marker_cluster: ^1.4.0
  intl: ^0.20.1
  file_picker: ^10.1.2
  csv: ^6.0.0
  geolocator: ^13.0.1
  logging: ^1.3.0
  collection: ^1.19.0
  flutter_map_location_marker: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
  - assets/dove.json
  - assets/tower3.svg
  - assets/tower4.svg
  - assets/tower5.svg
  - assets/tower6.svg
  - assets/tower8.svg
  - assets/tower10.svg
  - assets/tower12.svg
  - assets/tower_unringable.svg
  - assets/icon/bell.png
